// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

// Import all method implementations
import { registerMethod } from "./index"
import { initializeWebview } from "./initializeWebview"
import { onDidShowAnnouncement } from "./onDidShowAnnouncement"
import { scrollToSettings } from "./scrollToSettings"
import { subscribeToAccountButtonClicked } from "./subscribeToAccountButtonClicked"
import { subscribeToAddToInput } from "./subscribeToAddToInput"
import { subscribeToChatButtonClicked } from "./subscribeToChatButtonClicked"
import { subscribeToDidBecomeVisible } from "./subscribeToDidBecomeVisible"
import { subscribeToFocusChatInput } from "./subscribeToFocusChatInput"
import { subscribeToHistoryButtonClicked } from "./subscribeToHistoryButtonClicked"
import { subscribeToMcpButtonClicked } from "./subscribeToMcpButtonClicked"
import { subscribeToPartialMessage } from "./subscribeToPartialMessage"
import { subscribeToRelinquishControl } from "./subscribeToRelinquishControl"
import { subscribeToSettingsButtonClicked } from "./subscribeToSettingsButtonClicked"
import { subscribeToTheme } from "./subscribeToTheme"

// Register all ui service methods
export function registerAllMethods(): void {
	// Register each method with the registry
	registerMethod("initializeWebview", initializeWebview)
	registerMethod("onDidShowAnnouncement", onDidShowAnnouncement)
	registerMethod("scrollToSettings", scrollToSettings)
	registerMethod("subscribeToAccountButtonClicked", subscribeToAccountButtonClicked)
	registerMethod("subscribeToAddToInput", subscribeToAddToInput)
	registerMethod("subscribeToChatButtonClicked", subscribeToChatButtonClicked)
	registerMethod("subscribeToDidBecomeVisible", subscribeToDidBecomeVisible)
	registerMethod("subscribeToFocusChatInput", subscribeToFocusChatInput)
	registerMethod("subscribeToHistoryButtonClicked", subscribeToHistoryButtonClicked)
	registerMethod("subscribeToMcpButtonClicked", subscribeToMcpButtonClicked)
	registerMethod("subscribeToPartialMessage", subscribeToPartialMessage)
	registerMethod("subscribeToRelinquishControl", subscribeToRelinquishControl)
	registerMethod("subscribeToSettingsButtonClicked", subscribeToSettingsButtonClicked)
	registerMethod("subscribeToTheme", subscribeToTheme)
}