import { TemplateEngine } from "../../templates/TemplateEngine"
import type { PromptVariant, SystemPromptContext } from "../../types"
import { getPromptTranslation } from "../../../i18n"

export async function getToolUseExamplesSection(_variant: PromptVariant, context: SystemPromptContext): Promise<string> {
	const t = getPromptTranslation(context)
	// Return the placeholder that will be replaced with actual tools
	const focusChainEnabled = context.focusChainSettings?.enabled

	const template = [
		t.toolUseExamples.title,
		"",
		t.toolUseExamples.example1,
		"",
		"<execute_command>",
		"<command>npm run dev</command>",
		"<requires_approval>false</requires_approval>",
		"{{FOCUS_CHAIN_EXAMPLE_BASH}}</execute_command>",
		"",
		t.toolUseExamples.example2,
		"",
		"<write_to_file>",
		"<path>src/frontend-config.json</path>",
		"<content>",
		"{",
		'  "apiEndpoint": "https://api.example.com",',
		'  "theme": {',
		'    "primaryColor": "#007bff",',
		'    "secondaryColor": "#6c757d",',
		'    "fontFamily": "Arial, sans-serif"',
		"  },",
		'  "features": {',
		'    "darkMode": true,',
		'    "notifications": true,',
		'    "analytics": false',
		"  },",
		'  "version": "1.0.0"',
		"}",
		"</content>",
		"{{FOCUS_CHAIN_EXAMPLE_NEW_FILE}}</write_to_file>",
		"",
		t.toolUseExamples.example3,
		"",
		"<new_task>",
		"<context>",
		t.toolUseExamples.newTaskContext,
		"</context>",
		"</new_task>",
		"",
		t.toolUseExamples.example4,
		"",
		"<replace_in_file>",
		"<path>src/components/App.tsx</path>",
		"<diff>",
		"------- SEARCH",
		"import React from 'react';",
		"=======",
		"import React, { useState } from 'react';",
		"+++++++ REPLACE",
		"",
		"------- SEARCH",
		"function handleSubmit() {",
		"  saveData();",
		"  setLoading(false);",
		"}",
		"",
		"=======",
		"+++++++ REPLACE",
		"",
		"------- SEARCH",
		"return (",
		"  <div>",
		"=======",
		"function handleSubmit() {",
		"  saveData();",
		"  setLoading(false);",
		"}",
		"",
		"return (",
		"  <div>",
		"+++++++ REPLACE",
		"</diff>",
		"{{FOCUS_CHAIN_EXAMPLE_EDIT}}</replace_in_file>",
		"",
		"",
		t.toolUseExamples.example5,
		"",
		"<use_mcp_tool>",
		"<server_name>weather-server</server_name>",
		"<tool_name>get_forecast</tool_name>",
		"<arguments>",
		"{",
		'  "city": "San Francisco",',
		'  "days": 5',
		"}",
		"</arguments>",
		"</use_mcp_tool>",
		"",
		t.toolUseExamples.example6,
		"",
		"<use_mcp_tool>",
		"<server_name>github.com/modelcontextprotocol/servers/tree/main/src/github</server_name>",
		"<tool_name>create_issue</tool_name>",
		"<arguments>",
		"{",
		'  "owner": "octocat2",',
		'  "repo": "hello-world",',
		'  "title": "Found a bug",',
		'  "body": "I\'m having a problem with this.",',
		'  "labels": ["bug", "help wanted"],',
		'  "assignees": ["octocat"]',
		"}",
		"</arguments>",
		"</use_mcp_tool>",
	].join("\n")

	return new TemplateEngine().resolve(template, context, {
		FOCUS_CHAIN_EXAMPLE_BASH: focusChainEnabled ? t.toolUseExamples.bashProgress : "",
		FOCUS_CHAIN_EXAMPLE_NEW_FILE: focusChainEnabled ? t.toolUseExamples.newFileProgress : "",
		FOCUS_CHAIN_EXAMPLE_EDIT: focusChainEnabled ? t.toolUseExamples.editProgress : "",
	})
}
